package io.github.atrosinenko.kbdysch

object InvokerConstants {
  val SyscallDescriptionDirectory = "../descriptions"
  val GeneratedInvokerDirectory = "../runtime/generated"

  val InvokerNotice = Seq(
    "// AUTOGENERATED! DO NOT EDIT!",
    "// Syscall descriptions from the Syzkaller project are used.",
    "",
  )

  def InvokerHeader = Seq(
    "#include \"kbdysch/kbdysch.h\"",
    "#include \"kbdysch/invoker-utils.h\"",
    "#include \"kbdysch/mutator-interface.h\"",
    "#include \"kbdysch/api_defs.h\"",
    "",
    "#include <syscall.h>",
    "",
    s"static struct success_rate_info ${SuccessRateVar};",
    "",
  )

  val Q = '"'

  val MaybeUnused = "__attribute__((unused))"
  val InvokerStateArgDeclaration = "struct fuzzer_state *state"
  val InvokerEntryPoint = s"void invoke_next_op($InvokerStateArgDeclaration, uint8_t opc) {"
  val PatchInvokerName = "invoke___patch"

  val SuccessRateAllocator = "mutator_allocate_success_rate"
  val SuccessRateReporter = "mutator_report_success_or_failure"
  val SuccessRateVar = "invoker_success_rate"

  val InvokerState = "state"

  val PartInd = "part"
}
