package io.github.atrosinenko.kbdysch

object InvokerConstants {
  val SyscallDescriptionDirectory = "../descriptions"
  val GeneratedInvokerDirectory = "../runtime/generated"

  val InvokerNotice = Seq(
    "// AUTOGENERATED! DO NOT EDIT!",
    "// Syscall descriptions from the Syzkaller project are used.",
    "",
  )

  val InvokerHeader = Seq(
    "#include \"kbdysch/kbdysch.h\"",
    "#include \"kbdysch/invoker-utils.h\"",
    "#include \"kbdysch/api_defs.h\"",
    "",
    "#include <syscall.h>",
    "",
  )

  val Q = '"'

  val MaybeUnused = "__attribute__((unused))"
  val InvokerStateArgDeclaration = "struct fuzzer_state *state"
  val InvokerEntryPoint = s"void invoke_next_op($InvokerStateArgDeclaration, uint8_t opc) {"
  val PatchInvokerName = "invoke___patch"

  val InvokerState = "state"

  val PartInd = "part"
}
