name: Post-commit check
on: [push]
jobs:
  generate-invokers:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
      - name: Install Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'sbt'
      - name: Generate invokers
        run: ./update_invokers.sh
      - name: Save invokers as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: invokers
          path: runtime/generated

  build-and-test:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    needs: generate-invokers
    strategy:
      matrix:
        include:
          - compiler: clang
            cmake_opts: ''
          - compiler: clang
            cmake_opts: '-DCMAKE_C_FLAGS="-fsanitize=undefined"'
          - compiler: clang
            cmake_opts: '-DCMAKE_C_FLAGS="-fsanitize=address"'
          - compiler: afl-clang-fast
            cmake_opts: '-DKBDYSCH_PERFORM_AFL_TESTS=ON'
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
      - name: Install other dependencies
        run: sudo apt-get install --no-install-recommends -y cmake libpth-dev clang afl-clang
      - name: Restore invokers from artifacts
        uses: actions/download-artifact@v3
        with:
          name: invokers
          path: runtime/generated
      - name: Run CMake
        run: cmake -S . -B ./build -DUSE_LKL=OFF -DUSE_DUMMY_LKL=ON -DCMAKE_C_COMPILER=${{ matrix.compiler }} ${{ matrix.cmake_opts }}
      - name: Build harnesses
        run: cmake --build ./build
      - name: Run tests
        run: ctest --output-on-failure --test-output-size-failed 65536 --test-dir ./build
