name: Post-commit check
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - name: Perform checkout
        uses: actions/checkout@v2
      - name: Install Java 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install other dependencies
        run: sudo apt-get install -y cmake libpth-dev
      - name: Cache Scala packages
        uses: actions/cache@v2
        with:
          key: sbt-cache
          path: |
            ~/.sbt/1.0/zinc/org.scala-sbt
            ~/.sbt/boot/scala-*
            ~/.ivy/cache
      - name: Generate invokers
        run: ./update_invokers.sh
      - name: Run CMake
        run: cmake -S . -B ./build -DUSE_LKL=OFF
      - name: Build harnesses
        run: cmake --build ./build
