name: Build kBdysch harnesses
on: [push]
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Download pre-generated invokers
        uses: actions/download-artifact@v2
        with:
          name: invokers
          path: runtime/generated
      - name: Configure
        run: cmake -S runtime -B build -DUSE_LKL=FALSE
      - name: Build
        run: make -C build
